/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root"
import { Route as LoginImport } from "./routes/login"
import { Route as LayoutImport } from "./routes/_layout"
import { Route as LayoutIndexImport } from "./routes/_layout/index"
import { Route as LayoutTemplatesImport } from "./routes/_layout/templates"
import { Route as LayoutProfileImport } from "./routes/_layout/profile"
import { Route as LayoutComponentsIndexImport } from "./routes/_layout/components/index"
import { Route as LayoutComponentsTextareasImport } from "./routes/_layout/components/textareas"
import { Route as LayoutComponentsSwitchsImport } from "./routes/_layout/components/switchs"
import { Route as LayoutComponentsSelectsImport } from "./routes/_layout/components/selects"
import { Route as LayoutComponentsSelectMenusImport } from "./routes/_layout/components/select-menus"
import { Route as LayoutComponentsInputsImport } from "./routes/_layout/components/inputs"
import { Route as LayoutComponentsDropdownsImport } from "./routes/_layout/components/dropdowns"
import { Route as LayoutComponentsButtonsImport } from "./routes/_layout/components/buttons"
import { Route as LayoutComponentsButtonGroupsImport } from "./routes/_layout/components/button-groups"
import { Route as LayoutComponentsBadgesImport } from "./routes/_layout/components/badges"
import { Route as LayoutComponentsAvatarsImport } from "./routes/_layout/components/avatars"

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: "/_layout",
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutTemplatesRoute = LayoutTemplatesImport.update({
  id: "/templates",
  path: "/templates",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutProfileRoute = LayoutProfileImport.update({
  id: "/profile",
  path: "/profile",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComponentsIndexRoute = LayoutComponentsIndexImport.update({
  id: "/components/",
  path: "/components/",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComponentsTextareasRoute = LayoutComponentsTextareasImport.update({
  id: "/components/textareas",
  path: "/components/textareas",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComponentsSwitchsRoute = LayoutComponentsSwitchsImport.update({
  id: "/components/switchs",
  path: "/components/switchs",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComponentsSelectsRoute = LayoutComponentsSelectsImport.update({
  id: "/components/selects",
  path: "/components/selects",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComponentsSelectMenusRoute =
  LayoutComponentsSelectMenusImport.update({
    id: "/components/select-menus",
    path: "/components/select-menus",
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutComponentsInputsRoute = LayoutComponentsInputsImport.update({
  id: "/components/inputs",
  path: "/components/inputs",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComponentsDropdownsRoute = LayoutComponentsDropdownsImport.update({
  id: "/components/dropdowns",
  path: "/components/dropdowns",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComponentsButtonsRoute = LayoutComponentsButtonsImport.update({
  id: "/components/buttons",
  path: "/components/buttons",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComponentsButtonGroupsRoute =
  LayoutComponentsButtonGroupsImport.update({
    id: "/components/button-groups",
    path: "/components/button-groups",
    getParentRoute: () => LayoutRoute,
  } as any)

const LayoutComponentsBadgesRoute = LayoutComponentsBadgesImport.update({
  id: "/components/badges",
  path: "/components/badges",
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComponentsAvatarsRoute = LayoutComponentsAvatarsImport.update({
  id: "/components/avatars",
  path: "/components/avatars",
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_layout": {
      id: "/_layout"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      id: "/login"
      path: "/login"
      fullPath: "/login"
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/_layout/profile": {
      id: "/_layout/profile"
      path: "/profile"
      fullPath: "/profile"
      preLoaderRoute: typeof LayoutProfileImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/templates": {
      id: "/_layout/templates"
      path: "/templates"
      fullPath: "/templates"
      preLoaderRoute: typeof LayoutTemplatesImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/": {
      id: "/_layout/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/avatars": {
      id: "/_layout/components/avatars"
      path: "/components/avatars"
      fullPath: "/components/avatars"
      preLoaderRoute: typeof LayoutComponentsAvatarsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/badges": {
      id: "/_layout/components/badges"
      path: "/components/badges"
      fullPath: "/components/badges"
      preLoaderRoute: typeof LayoutComponentsBadgesImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/button-groups": {
      id: "/_layout/components/button-groups"
      path: "/components/button-groups"
      fullPath: "/components/button-groups"
      preLoaderRoute: typeof LayoutComponentsButtonGroupsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/buttons": {
      id: "/_layout/components/buttons"
      path: "/components/buttons"
      fullPath: "/components/buttons"
      preLoaderRoute: typeof LayoutComponentsButtonsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/dropdowns": {
      id: "/_layout/components/dropdowns"
      path: "/components/dropdowns"
      fullPath: "/components/dropdowns"
      preLoaderRoute: typeof LayoutComponentsDropdownsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/inputs": {
      id: "/_layout/components/inputs"
      path: "/components/inputs"
      fullPath: "/components/inputs"
      preLoaderRoute: typeof LayoutComponentsInputsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/select-menus": {
      id: "/_layout/components/select-menus"
      path: "/components/select-menus"
      fullPath: "/components/select-menus"
      preLoaderRoute: typeof LayoutComponentsSelectMenusImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/selects": {
      id: "/_layout/components/selects"
      path: "/components/selects"
      fullPath: "/components/selects"
      preLoaderRoute: typeof LayoutComponentsSelectsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/switchs": {
      id: "/_layout/components/switchs"
      path: "/components/switchs"
      fullPath: "/components/switchs"
      preLoaderRoute: typeof LayoutComponentsSwitchsImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/textareas": {
      id: "/_layout/components/textareas"
      path: "/components/textareas"
      fullPath: "/components/textareas"
      preLoaderRoute: typeof LayoutComponentsTextareasImport
      parentRoute: typeof LayoutImport
    }
    "/_layout/components/": {
      id: "/_layout/components/"
      path: "/components"
      fullPath: "/components"
      preLoaderRoute: typeof LayoutComponentsIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutProfileRoute: typeof LayoutProfileRoute
  LayoutTemplatesRoute: typeof LayoutTemplatesRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutComponentsAvatarsRoute: typeof LayoutComponentsAvatarsRoute
  LayoutComponentsBadgesRoute: typeof LayoutComponentsBadgesRoute
  LayoutComponentsButtonGroupsRoute: typeof LayoutComponentsButtonGroupsRoute
  LayoutComponentsButtonsRoute: typeof LayoutComponentsButtonsRoute
  LayoutComponentsDropdownsRoute: typeof LayoutComponentsDropdownsRoute
  LayoutComponentsInputsRoute: typeof LayoutComponentsInputsRoute
  LayoutComponentsSelectMenusRoute: typeof LayoutComponentsSelectMenusRoute
  LayoutComponentsSelectsRoute: typeof LayoutComponentsSelectsRoute
  LayoutComponentsSwitchsRoute: typeof LayoutComponentsSwitchsRoute
  LayoutComponentsTextareasRoute: typeof LayoutComponentsTextareasRoute
  LayoutComponentsIndexRoute: typeof LayoutComponentsIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProfileRoute: LayoutProfileRoute,
  LayoutTemplatesRoute: LayoutTemplatesRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutComponentsAvatarsRoute: LayoutComponentsAvatarsRoute,
  LayoutComponentsBadgesRoute: LayoutComponentsBadgesRoute,
  LayoutComponentsButtonGroupsRoute: LayoutComponentsButtonGroupsRoute,
  LayoutComponentsButtonsRoute: LayoutComponentsButtonsRoute,
  LayoutComponentsDropdownsRoute: LayoutComponentsDropdownsRoute,
  LayoutComponentsInputsRoute: LayoutComponentsInputsRoute,
  LayoutComponentsSelectMenusRoute: LayoutComponentsSelectMenusRoute,
  LayoutComponentsSelectsRoute: LayoutComponentsSelectsRoute,
  LayoutComponentsSwitchsRoute: LayoutComponentsSwitchsRoute,
  LayoutComponentsTextareasRoute: LayoutComponentsTextareasRoute,
  LayoutComponentsIndexRoute: LayoutComponentsIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  "": typeof LayoutRouteWithChildren
  "/login": typeof LoginRoute
  "/profile": typeof LayoutProfileRoute
  "/templates": typeof LayoutTemplatesRoute
  "/": typeof LayoutIndexRoute
  "/components/avatars": typeof LayoutComponentsAvatarsRoute
  "/components/badges": typeof LayoutComponentsBadgesRoute
  "/components/button-groups": typeof LayoutComponentsButtonGroupsRoute
  "/components/buttons": typeof LayoutComponentsButtonsRoute
  "/components/dropdowns": typeof LayoutComponentsDropdownsRoute
  "/components/inputs": typeof LayoutComponentsInputsRoute
  "/components/select-menus": typeof LayoutComponentsSelectMenusRoute
  "/components/selects": typeof LayoutComponentsSelectsRoute
  "/components/switchs": typeof LayoutComponentsSwitchsRoute
  "/components/textareas": typeof LayoutComponentsTextareasRoute
  "/components": typeof LayoutComponentsIndexRoute
}

export interface FileRoutesByTo {
  "/login": typeof LoginRoute
  "/profile": typeof LayoutProfileRoute
  "/templates": typeof LayoutTemplatesRoute
  "/": typeof LayoutIndexRoute
  "/components/avatars": typeof LayoutComponentsAvatarsRoute
  "/components/badges": typeof LayoutComponentsBadgesRoute
  "/components/button-groups": typeof LayoutComponentsButtonGroupsRoute
  "/components/buttons": typeof LayoutComponentsButtonsRoute
  "/components/dropdowns": typeof LayoutComponentsDropdownsRoute
  "/components/inputs": typeof LayoutComponentsInputsRoute
  "/components/select-menus": typeof LayoutComponentsSelectMenusRoute
  "/components/selects": typeof LayoutComponentsSelectsRoute
  "/components/switchs": typeof LayoutComponentsSwitchsRoute
  "/components/textareas": typeof LayoutComponentsTextareasRoute
  "/components": typeof LayoutComponentsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  "/_layout": typeof LayoutRouteWithChildren
  "/login": typeof LoginRoute
  "/_layout/profile": typeof LayoutProfileRoute
  "/_layout/templates": typeof LayoutTemplatesRoute
  "/_layout/": typeof LayoutIndexRoute
  "/_layout/components/avatars": typeof LayoutComponentsAvatarsRoute
  "/_layout/components/badges": typeof LayoutComponentsBadgesRoute
  "/_layout/components/button-groups": typeof LayoutComponentsButtonGroupsRoute
  "/_layout/components/buttons": typeof LayoutComponentsButtonsRoute
  "/_layout/components/dropdowns": typeof LayoutComponentsDropdownsRoute
  "/_layout/components/inputs": typeof LayoutComponentsInputsRoute
  "/_layout/components/select-menus": typeof LayoutComponentsSelectMenusRoute
  "/_layout/components/selects": typeof LayoutComponentsSelectsRoute
  "/_layout/components/switchs": typeof LayoutComponentsSwitchsRoute
  "/_layout/components/textareas": typeof LayoutComponentsTextareasRoute
  "/_layout/components/": typeof LayoutComponentsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ""
    | "/login"
    | "/profile"
    | "/templates"
    | "/"
    | "/components/avatars"
    | "/components/badges"
    | "/components/button-groups"
    | "/components/buttons"
    | "/components/dropdowns"
    | "/components/inputs"
    | "/components/select-menus"
    | "/components/selects"
    | "/components/switchs"
    | "/components/textareas"
    | "/components"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/login"
    | "/profile"
    | "/templates"
    | "/"
    | "/components/avatars"
    | "/components/badges"
    | "/components/button-groups"
    | "/components/buttons"
    | "/components/dropdowns"
    | "/components/inputs"
    | "/components/select-menus"
    | "/components/selects"
    | "/components/switchs"
    | "/components/textareas"
    | "/components"
  id:
    | "__root__"
    | "/_layout"
    | "/login"
    | "/_layout/profile"
    | "/_layout/templates"
    | "/_layout/"
    | "/_layout/components/avatars"
    | "/_layout/components/badges"
    | "/_layout/components/button-groups"
    | "/_layout/components/buttons"
    | "/_layout/components/dropdowns"
    | "/_layout/components/inputs"
    | "/_layout/components/select-menus"
    | "/_layout/components/selects"
    | "/_layout/components/switchs"
    | "/_layout/components/textareas"
    | "/_layout/components/"
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/login"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/profile",
        "/_layout/templates",
        "/_layout/",
        "/_layout/components/avatars",
        "/_layout/components/badges",
        "/_layout/components/button-groups",
        "/_layout/components/buttons",
        "/_layout/components/dropdowns",
        "/_layout/components/inputs",
        "/_layout/components/select-menus",
        "/_layout/components/selects",
        "/_layout/components/switchs",
        "/_layout/components/textareas",
        "/_layout/components/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_layout/profile": {
      "filePath": "_layout/profile.tsx",
      "parent": "/_layout"
    },
    "/_layout/templates": {
      "filePath": "_layout/templates.tsx",
      "parent": "/_layout"
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/avatars": {
      "filePath": "_layout/components/avatars.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/badges": {
      "filePath": "_layout/components/badges.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/button-groups": {
      "filePath": "_layout/components/button-groups.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/buttons": {
      "filePath": "_layout/components/buttons.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/dropdowns": {
      "filePath": "_layout/components/dropdowns.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/inputs": {
      "filePath": "_layout/components/inputs.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/select-menus": {
      "filePath": "_layout/components/select-menus.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/selects": {
      "filePath": "_layout/components/selects.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/switchs": {
      "filePath": "_layout/components/switchs.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/textareas": {
      "filePath": "_layout/components/textareas.tsx",
      "parent": "/_layout"
    },
    "/_layout/components/": {
      "filePath": "_layout/components/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
