import { createFileRoute } from "@tanstack/react-router"
import { Badge } from "src/shared/ui"
import { ResizeContainer } from "src/widgets/resize-container"
import { Stack } from "src/widgets/stack"

export const Route = createFileRoute("/_layout/elements/badges")({
	component: RouteComponent,
})

function RouteComponent() {
	return (
		<>
			<ResizeContainer
				title={"With border"}
				color={"white"}
			>
				<Stack size={"sm"}>
					<Badge>Badge</Badge>
					<Badge color={"red"}>Badge</Badge>
					<Badge color={"yellow"}>Badge</Badge>
					<Badge color={"green"}>Badge</Badge>
					<Badge color={"blue"}>Badge</Badge>
					<Badge color={"indigo"}>Badge</Badge>
					<Badge color={"purple"}>Badge</Badge>
					<Badge color={"pink"}>Badge</Badge>
				</Stack>
			</ResizeContainer>
			<ResizeContainer
				title={"With border and dot"}
				color={"white"}
			>
				<Stack size={"xs"}>
					<Badge
						dot={true}
						color={"default"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						color={"red"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						color={"yellow"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						color={"green"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						color={"blue"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						color={"indigo"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						color={"purple"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						color={"pink"}
					>
						Badge
					</Badge>
				</Stack>
			</ResizeContainer>
			<ResizeContainer
				title={"Pill with border"}
				color={"white"}
			>
				<Stack size={"sm"}>
					<Badge
						pill={true}
						color={"default"}
					>
						Badge
					</Badge>
					<Badge
						pill={true}
						color={"red"}
					>
						Badge
					</Badge>
					<Badge
						pill={true}
						color={"yellow"}
					>
						Badge
					</Badge>
					<Badge
						pill={true}
						color={"green"}
					>
						Badge
					</Badge>
					<Badge
						pill={true}
						color={"blue"}
					>
						Badge
					</Badge>
					<Badge
						pill={true}
						color={"indigo"}
					>
						Badge
					</Badge>
					<Badge
						pill={true}
						color={"purple"}
					>
						Badge
					</Badge>
					<Badge
						pill={true}
						color={"pink"}
					>
						Badge
					</Badge>
				</Stack>
			</ResizeContainer>
			<ResizeContainer
				title={"Pill with border and dot"}
				color={"white"}
			>
				<Stack size={"xs"}>
					<Badge
						dot={true}
						pill={true}
						color={"default"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						pill={true}
						color={"red"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						pill={true}
						color={"yellow"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						pill={true}
						color={"green"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						pill={true}
						color={"blue"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						pill={true}
						color={"indigo"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						pill={true}
						color={"purple"}
					>
						Badge
					</Badge>
					<Badge
						dot={true}
						pill={true}
						color={"pink"}
					>
						Badge
					</Badge>
				</Stack>
			</ResizeContainer>
			<ResizeContainer
				title={"With border and remove button"}
				color={"white"}
			>
				<Stack size={"xs"}>
					<Badge
						button={true}
						color={"default"}
					>
						Badge
					</Badge>
					<Badge
						button={true}
						color={"red"}
					>
						Badge
					</Badge>
					<Badge
						button={true}
						color={"yellow"}
					>
						Badge
					</Badge>
					<Badge
						button={true}
						color={"green"}
					>
						Badge
					</Badge>
					<Badge
						button={true}
						color={"blue"}
					>
						Badge
					</Badge>
					<Badge
						button={true}
						color={"indigo"}
					>
						Badge
					</Badge>
					<Badge
						button={true}
						color={"purple"}
					>
						Badge
					</Badge>
					<Badge
						button={true}
						color={"pink"}
					>
						Badge
					</Badge>
				</Stack>
			</ResizeContainer>
			<ResizeContainer
				title={"Flat"}
				color={"white"}
			>
				<Stack size={"sm"}>
					<Badge
						flat={true}
						color={"default"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						color={"red"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						color={"yellow"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						color={"green"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						color={"blue"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						color={"indigo"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						color={"purple"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						color={"pink"}
					>
						Badge
					</Badge>
				</Stack>
			</ResizeContainer>
			<ResizeContainer
				title={"Flat pill"}
				color={"white"}
			>
				<Stack size={"sm"}>
					<Badge
						flat={true}
						pill={true}
						color={"default"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						pill={true}
						color={"red"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						pill={true}
						color={"yellow"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						pill={true}
						color={"green"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						pill={true}
						color={"blue"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						pill={true}
						color={"indigo"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						pill={true}
						color={"purple"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						pill={true}
						color={"pink"}
					>
						Badge
					</Badge>
				</Stack>
			</ResizeContainer>
			<ResizeContainer
				title={"Flat with dot"}
				color={"white"}
			>
				<Stack size={"sm"}>
					<Badge
						flat={true}
						dot={true}
						color={"default"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						dot={true}
						color={"red"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						dot={true}
						color={"yellow"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						dot={true}
						color={"green"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						dot={true}
						color={"blue"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						dot={true}
						color={"indigo"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						dot={true}
						color={"purple"}
					>
						Badge
					</Badge>
					<Badge
						flat={true}
						dot={true}
						color={"pink"}
					>
						Badge
					</Badge>
				</Stack>
			</ResizeContainer>
		</>
	)
}
